### ISSUE TITLE
EP01 - 网页中使用中文字体

### ISSUE THREAD

**Issue by davinma** [davinma/blog#1]
# 简介

1. 作为使用汉字最大量的国家，我们可用的汉字字库只有 421 种，而日本有 2973 种。
2. 字体盗版
3. 微软雅黑

# 免费中文字体

1. 思源黑体：
  Adobe 在线字体库 **Typekit** 与 **Google** 一起正式发布了新款开源字体。

2. 方正字库免费字体:
  方正黑体、方正书宋、方正仿宋、方正楷体四种免费字体。

3. 站酷（ZCOOL）字体:
  站酷高端黑、站酷快乐体两种免费字体。

其他免费中文字体参考：
http://zenozeng.github.io/Free-Chinese-Fonts/

# 版权

可以通过 `font-family` 方式引用字体，禁止通过 CSS 中 `@font-face` 方式内嵌字体。

例子一：
``` CSS
.example1 {
    font-family: "微软雅黑", Helvetica, Arial, sans-serif
}
```

例子二：
``` CSS
@font-face {
  font-family: 'MyWebFont';
  src: url('webfont.eot'); /* IE9 Compat Modes */
  src: url('webfont.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('webfont.woff2') format('woff2'), /* Super Modern Browsers */
       url('webfont.woff') format('woff'), /* Pretty Modern Browsers */
       url('webfont.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('webfont.svg#svgFontName') format('svg'); /* Legacy iOS */
}
.example2 {
    font-family: "MyWebFont", Helvetica, Arial, sans-serif;
}
```

# 文字对齐

左对齐
``` CSS
.example3 {
    text-align: left;
}
```

居中
``` CSS
.example4 {
    text-align: center;
}
```

右对齐
``` CSS
.example5 {
    text-align: right;
}
```
