### ISSUE TITLE
EP04 - background-color with RGBa in IE 6-8

### ISSUE THREAD

**Issue by davinma** [davinma/blog#5]
````` CSS
div {
    background: rgb(255, 255, 255) transparent; /* default fallback */
    background: rgba(255, 255, 255,0.17); /* nice browsers */
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#2BFFFFFF, endColorstr=#2BFFFFFF); /* IE 6/7 */
    -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#2BFFFFFF, endColorstr=#2BFFFFFF)"; /* IE 8/9 */
}
:root .dock_wrap span.cur {
    filter: none /* remove filter in IE9 */
}
`````

But in IE 6-8, these is a bug at above style, click through a div to underlying elements if it's a link tag.

#### Solution
1. [BT9029: 在 IE 中被透明元素遮挡的元素仍能响应鼠标事件](http://w3help.org/zh-cn/causes/BT9029)
2. [CSS Transparent Background](http://davidshariff.com/blog/css-transparent-background/)
